106 Implement audio playing for daily news
ActualIA/app pull request #108
Opened 2024-04-25 17:36 UTC by ClementJosso

2024-04-25 23:17 UTC, ClementJosso reviewed
This commit is only meant as a way to let Jacopo work on it with me, it doesn't add a completed feature

2024-05-01 21:13 UTC, ClementJosso commented
As of right now, we are making progress towards having a working audio player. We can know play files that we write on the device, but the pause doesn't work, and the call to the generate-audio function doesn't work as well

2024-05-02 19:30 UTC, Thechi2000 reviewed
Works great overall ! The automatic download of the audio files is great to avoid latency, but I think we could have a toast to tell the user when it is not already available.

2024-05-02 19:30 UTC, Thechi2000 commented on lib/widgets/play_button.dart
> +                color: Color.fromARGB(255, 68, 159, 166),
Couldn't we use colors from the App's theme, for consistency ?

2024-05-02 19:30 UTC, Thechi2000 commented on test/widgets/play_button.dart
> +    // await tester.pumpWidget(const App());
Those comments seems out of place, probably a copy-paste ?

2024-05-02 19:30 UTC, Thechi2000 commented on test/widgets/source_view.dart
> +    const String date = "1111-11-11";
We should probably use dates after the epoch (01/01/1970) to avoid potential issuesn

2024-05-02 19:30 UTC, Thechi2000 commented on lib/viewmodels/news.dart
> +  }
Those lines are not covered, isn't there a way to do this ? Perhaps by using dependency injection for `getApplicationDocumentsDirectory()`.

2024-05-02 19:30 UTC, pmdlt commented on lib/viewmodels/news.dart
> +    if (news.transcriptId == -1) {
I think it would be worth adding comments here, I didn't understand at first what this check did.

2024-05-02 19:30 UTC, pmdlt commented on lib/viewmodels/news.dart
> +    audio ??= await generateAudio(news.transcriptId);
How does error handling work here? What happens if the Edge generate-audio function returns something other than 200?

2024-05-02 19:30 UTC, pmdlt commented on lib/viewmodels/news.dart
> +    audio ??= await generateAudio(news.transcriptId);
I mean, wouldn't it be worth putting the await in the try, and displaying a clear error message to the user?

2024-05-02 19:30 UTC, pmdlt commented on lib/viewmodels/news.dart
> +    audio ??= await generateAudio(news.transcriptId);
(you can also decide to leave it for another PR)

2024-05-02 19:30 UTC, pmdlt commented on lib/viewmodels/news.dart
> +      log('Error downloading audio file: $e', level: Level.WARNING.value);
do you think it's possible to display a clear error to the user?

2024-05-02 19:37 UTC, ClementJosso commented on lib/viewmodels/news.dart
> +      log('Error downloading audio file: $e', level: Level.WARNING.value);
Do you mean displaying it on the screen ? We could but I don't see any case where this error could happen to be honest, we're catching the error in case it happens but since we corrected the function it has never thrown any

2024-05-02 19:39 UTC, ClementJosso commented on lib/viewmodels/news.dart
> +    audio ??= await generateAudio(news.transcriptId);
What do you mean other than 200 ? Is it a code the function sends on success ?

2024-05-02 19:45 UTC, pmdlt requested changes

2024-05-02 19:45 UTC, pmdlt commented on supabase/functions/generate-transcript/index.ts
> +  } catch (_) {}
Why a try/catch here if we don't care of the catch ? @Thechi2000

2024-05-02 19:46 UTC, pmdlt commented on lib/viewmodels/news.dart
> +    audio ??= await generateAudio(news.transcriptId);
Yes, 200 on success, 400, 500, etc,. on errors

2024-05-02 19:47 UTC, pmdlt commented on lib/viewmodels/news.dart
> +      log('Error downloading audio file: $e', level: Level.WARNING.value);
An Internet problem, for example. But yes, @Thechi2000  is right, you can do that in a specific PR that takes care of displaying nice errors

2024-05-02 21:44 UTC, ClementJosso commented on supabase/functions/generate-transcript/index.ts
> +  } catch (_) {}
I suggest we do theses changes in another PR since it is not really related to the objective of this branch

2024-05-02 21:49 UTC, ClementJosso commented
I took notes of your comments and made changes. However, the toasts will be added in another PR, and I am unable to make some of the tests requested at the moment.

2024-05-02 22:01 UTC, pmdlt approved these changes
Thanks for the changes !

2024-05-02 22:59 UTC, Thechi2000 submitted a review, later dismissed
Let's merge that !

2024-05-02 23:22 UTC, Thechi2000 approved these changes

2024-05-03 04:30 UTC, loggerz approved these changes

2024-05-03 04:31 UTC, merged