111 refactor: handle onboarding status in the auth state listener
ActualIA/app pull request #113
Opened 2024-04-26 14:11 UTC by loggerz

2024-04-26 23:18 UTC, Thechi2000 requested changes
I tested on Android, everything works as expected. Good job !

I just have a few small comments on the code.

2024-04-26 23:18 UTC, Thechi2000 commented on lib/models/auth_model.dart
> +        print(user!.userMetadata);
```suggestion
```

Should be removed, since it contains confidential information.

2024-04-26 23:18 UTC, Thechi2000 commented on lib/models/auth_model.dart
> +      // isOnboardingRequired = true; // always show onboarding with test (non-google) accounts
Why is this commented ? I think the line should either be uncommented (always show onboarding), or completely removed (only on first time).

2024-04-26 23:18 UTC, Thechi2000 commented on lib/models/auth_model.dart
> +  Future<bool> setOnboardingIsDone() async {
I find the name a bit weird. I feel like a setter should take a value parameter, so we would have `setOnboardingCompletion(boolean completed)`, or `markOnboardingAsDone()` to only set it to true.

2024-04-27 10:15 UTC, LeanderCretegny commented on lib/models/auth_model.dart
> +      // isOnboardingRequired = true; // always show onboarding with test (non-google) accounts
If the onboarding is executed each time it could be annoying depending on what you are implementing or testing, but you also might need it to always be executed, hence the commented line that can simply be  uncommented.

2024-04-27 10:18 UTC, LeanderCretegny commented on lib/models/auth_model.dart
> +  Future<bool> setOnboardingIsDone() async {
As you said, we don't want to be able to mark it as anything else than true, hence the parameter is useless. Then regarding your renaming proposition, I find it completely equivalent.

2024-04-27 11:03 UTC, Thechi2000 commented on lib/models/auth_model.dart
> +      // isOnboardingRequired = true; // always show onboarding with test (non-google) accounts
IIUC, the line is only commented for debugging purpose. If this si correct, then it should be uncommented in the production code.

2024-04-27 19:51 UTC, loggerz commented on lib/models/auth_model.dart
> +      // isOnboardingRequired = true; // always show onboarding with test (non-google) accounts
It was not for debugging purprose, it was an older implementation. It should be removed, we might want to override the behavior for test account as suggested by the comment but this hasn't been clearly decided yet.
Thanks for catching this

2024-04-27 22:33 UTC, Thechi2000 approved these changes

2024-04-28 19:53 UTC, quartztz approved these changes
Had the same comments as Ludo before changes were made, glad to see it's fixed now :D looks good to me!

2024-04-29 07:09 UTC, merged