104 feat onboarding provider update
ActualIA/app pull request #117
Opened 2024-04-29 08:23 UTC by LeanderCretegny

This feature integrate the news providers selection to the onboarding wizard.

**To test**: 
 - Go to supabase and delete your google account to simulate a first  connection to the app 
 - Launch the app and connect yourself with your google account
 - Complete the onboarding wizard
 - Once wizard is completed you should be on the news page

2024-05-02 21:27 UTC, Thechi2000 requested changes
I did spot the following bugs:
- When going through the source's settings, the entries are added each time, without removing the old ones. When logging out then back in, I have to click "Google News several times to get rid of it.

On a clean user, I added Google News and `https://test.rss`, then went through the settings 2 times (without changing anything) and got:
![image](https://github.com/ActualIA/app/assets/70897464/d121f68f-9ce1-4e6a-8b4d-86e6044d6bf7)

Also, it is not very clear that the user has to type "Enter" to validate a RSS Feed, maybe something could be improved ? It took me to attempts where I thought it just did not work.

Also, I don't really like the way you handle the different selectors. I find it very error prone and dirty. Instead, I think that each selector should be associated with a metadata - the provider - and the display should directly use the `displayString()` method. This way, there would be no need of serializing and then deserializing the values. The code would be much nicer that way IMO.

2024-05-02 21:27 UTC, Thechi2000 commented on lib/models/providers.dart
> +  /// - GNews: `{"type", "gnews"}` todo change ',' by ':'
```suggestion
  /// - GNews: `{"type": "gnews"}`
```

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +            padding: const EdgeInsets.fromLTRB(0.0, 24.0, 0.0, 24.0),
Should you the theme's values, not hardcoded ones.

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +        maxLines: 2,
Should you the theme's values, not hardcoded ones.

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +            fontSize: 32.0),
Should you the theme's values, not hardcoded ones.

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +  const WizardSelectorTitle({this.title = "default title", super.key});
Does it really need a default title ? If yes, it would be more adapted to have an actual title instead of a placeholder.

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +      this.body = const Text("unimplemented"),
Like above, does it really need a default value ?

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +          padding: const EdgeInsets.fromLTRB(48.0, 48.0, 48.0, 48.0),
Should you the theme's values, not hardcoded ones.

2024-05-02 21:27 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +          runSpacing: 8.0,
Should you the theme's values, not hardcoded ones.

2024-05-02 21:37 UTC, LeanderCretegny commented on lib/widgets/wizard_widgets.dart
> +      this.body = const Text("unimplemented"),
In this case I find it relevant to act as a placeholder to help during development and testing. It is true that it is not required but it does not hurt and could even prove useful :)

2024-05-03 05:31 UTC, Thechi2000 submitted a review, later dismissed
Thanks for the changes, the code is much cleaner that way ! All the bugs are fixed now, good work.

2024-05-03 07:56 UTC, quartztz approved these changes
looks great on my end!

2024-05-03 08:55 UTC, Thechi2000 approved these changes

2024-05-03 09:06 UTC, pmdlt approved these changes

2024-05-03 09:06 UTC, merged