135 feat telegram provider
ActualIA/app pull request #137
Opened 2024-05-06 21:11 UTC by Thechi2000

2024-05-09 13:17 UTC, LeanderCretegny requested changes

2024-05-09 13:17 UTC, LeanderCretegny commented on lib/views/providers_wizard_view.dart
> +        ]),
Why not using widget WizardNavigationBottomBar from wizard_widgets.dart?

2024-05-09 13:17 UTC, LeanderCretegny commented on lib/views/providers_wizard_view.dart
> +      var items = widget.items as List<ProviderWidget>;
Why creating a local variable that will then be modified using setState()? It should be a private attribute of the State<> object holding the state for the item list mentioned in previous comment.

2024-05-09 13:17 UTC, LeanderCretegny commented on lib/widgets/wizard_widgets.dart
> +  void Function(ProviderWidget) onDelete;
attributes should be final (warning raised by my IDE: This class (or a class that this class inherits from) is marked as 'immutable', but one or more of its instance fields aren't final)

2024-05-09 13:17 UTC, LeanderCretegny commented on lib/widgets/wizard_widgets.dart
> +          onChanged: (v) => widget.values[index] = v);
Seems to have forgotten about setState here, and same point as above, I don't like the idea of modifying widget attribute using setState(), imo we should use a local variable inside the State<> object.

2024-05-09 13:17 UTC, LeanderCretegny commented on lib/widgets/wizard_widgets.dart
> +            }));
same point as above, I don't like the idea of modifying widget attribute using setState(), imo we should use a local variable inside the State<> object.

2024-05-09 15:31 UTC, Thechi2000 commented
All done, thanks for the tips ! I delegated handling the state of the edition to the ViewModel (as it should have been).

2024-05-09 21:04 UTC, LeanderCretegny requested changes
I have encountered a bug when running the code on my emulator, the provider widget is overflowing

2024-05-10 08:46 UTC, Thechi2000 commented
Thanks for the catch ! I fixed it, as well as replaced an `ListView` by a `Column` in the provider's widget.

2024-05-11 08:54 UTC, LeanderCretegny approved these changes
All bug found corrected, and code is great!

2024-05-11 14:44 UTC, pmdlt commented
I have several exceptions that happen when launching the app from the web and manipulating this view (creating and deleting sources), but I think it's related to the platform.

<img width="599" alt="image" src="https://github.com/ActualIA/app/assets/18498650/b13166f9-447f-41f6-8a84-46140e361abc">

2024-05-11 15:03 UTC, pmdlt approved these changes
Update: works well on an APK build generated for the occasion.
Ideally, we'd like to be able to choose Google News (or other providers that can only be selected once). But it's not so bad, let's leave it as a little improvement to be done before the official release :)

![image](https://github.com/ActualIA/app/assets/18498650/676e0d7b-4275-4a9e-bd2b-55ce6805c58e)

2024-05-11 15:04 UTC, pmdlt commented on supabase/functions/providers.ts
> +      if(url.startsWith("/")) {
Done

2024-05-11 15:04 UTC, pmdlt commented on supabase/functions/providers.ts
> +      // Filter news by AI according to user settings.
Done

2024-05-11 15:05 UTC, merged