136 feat add transcript news sharing options
ActualIA/app pull request #139
Opened 2024-05-08 17:30 UTC by pmdlt

This PR will add a multi-share button in the news-view.

2024-05-16 17:30 UTC, pmdlt commented
@Thechi2000 I'm sorry to bother you, but I don't understand why your test doesn't work.
`/home/runner/work/app/app/test/integration/sources.dart: User can consult source articles by tapping on them (failed)`
I tested several configurations, modified the test by updating the new requests returned by the Edge function, but there was nothing I could do...

2024-05-17 17:51 UTC, Thechi2000 commented
The news' view is stuck in an infinite loop, this needs to be fixed. It also blocked the testing of the new feature, so I cannot give feedback on it for now.

2024-05-17 19:56 UTC, LeanderCretegny commented on lib/views/news_view.dart
> +      body = Scaffold(
In my opinion we definitely should not put a scaffold inside another scaffold, but due to the short amount of time left, I suggest to leave it like that for now and open an issue to correct it in the future.

2024-05-17 19:58 UTC, ClementJosso approved these changes
Good work! I see that Leander has talked about the nested Scaffold, I think it can easily be fixed with some slight tweaking of the Master View, we can do that in another PR. Also, personal opinion but I think it would look better if the main button had the Button_theme instead of the Primary_theme.

2024-05-17 20:00 UTC, LeanderCretegny commented on lib/views/news_view.dart
> +            distance: 112,
Try to avoid raw number, it is better practice to declare a const variable as we did for the theme colors

2024-05-17 20:03 UTC, Thechi2000 reviewed
Awesome ! This works flawlessly, although I've a small complain:

If I understand correctly, only the first transcript can be shared ? This seems very user-unfriendly, especially since the button stays while scrolling down.

2024-05-17 20:09 UTC, pmdlt commented on lib/views/master_view.dart
I'll take care of it! Thanks :)

2024-05-17 20:14 UTC, LeanderCretegny requested changes
Apart from the magic number and the scaffold thing the code is very nice. I request change to remove the magic numbers, we'll deal with the scaffold another time.

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +      duration: const Duration(milliseconds: 250),
Same thing as above, avoid magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +      height: 56,
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +          elevation: 4,
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +              padding: const EdgeInsets.all(8),
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +    final step = 90.0 / (count - 1);
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +          1.0,
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +        duration: const Duration(milliseconds: 250),
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +          duration: const Duration(milliseconds: 250),
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +          bottom: 4.0 + offset.dy,
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +      elevation: 4,
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +      height: isBig ? 128 : 36,
Magic number

2024-05-17 20:14 UTC, LeanderCretegny commented on lib/widgets/share_button.dart
> +        color: Colors.grey.shade300,
Please use the theme defined lib/utils. If you need another color you can add it there.

2024-05-17 20:26 UTC, pmdlt commented
> Awesome ! This works flawlessly, although I've a small complain:
> 
> If I understand correctly, only the first transcript can be shared ? This seems very user-unfriendly, especially since the button stays while scrolling down.

Yes, I agree, that's why I was pushing for a separate view between news alone and the list. But I think it's ok to leave it like that for now as a PoC and we'll discuss it at the next meeting :)

2024-05-17 20:32 UTC, pmdlt commented on lib/views/news_view.dart
> +      body = Scaffold(
I've already thought about this, see https://stackoverflow.com/questions/60561552/multiple-scaffolds-for-each-page-inside-a-flutter-app

2024-05-17 20:35 UTC, ClementJosso approved these changes

2024-05-17 20:37 UTC, pmdlt commented on lib/views/news_view.dart
> +            distance: 112,
I agree in principle, but for this particular use case I don't think it's appropriate to turn them all into variables. And I accept this choice. It's a module that's grafted onto the app, not a main feature.

2024-05-17 20:38 UTC, merged