141 feat add alarm in onboarding
ActualIA/app pull request #142
Opened 2024-05-09 22:51 UTC by LeanderCretegny

Add screen to onboarding to set up a simple first alarm when user registers for the first time on the app.

To test: Go through the onboarding and try to add the alarm, test if each button behave as expected.

2024-05-10 05:49 UTC, quartztz requested changes
See my comment about themes for details about the requested changes ! Sorry >.<

2024-05-10 05:49 UTC, quartztz commented on lib/views/alarm_wizard.dart
> +    assetAudio = "assets/audio/boom.mp3";
wouldn't be against having a way to choose your own sound right around here ! nothing for now, just food for thought as to where we would implement that :D

2024-05-10 05:49 UTC, quartztz commented on lib/views/alarm_wizard.dart
> +      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
I understand why this was done : it's fast to implement and lays everything out nicely. I just don't know if it fully fits the design language of our application. Can and will this be discussed IRL ? Yes ! Can't wait to talk about it with you :)

2024-05-10 05:49 UTC, quartztz commented on lib/views/alarm_wizard.dart
> +        WizardNavigationBottomBar(
...especially because it breaks the display language for the "bottom bar" becoming a "bottom-ish bar we won't talk about". (follows from the previous comment, sorry)

2024-05-10 05:49 UTC, quartztz commented on lib/widgets/alarms_widget.dart
> +        margin: const EdgeInsets.all(20),
Please use the values provided by the Theme I made ! You've already done it for the text, there should be all the colors and spacings you need to make the app feel more cohesive. If there aren't, feel free to add ! But do check whether or not they're too similar to already existing values.

2024-05-10 05:49 UTC, quartztz commented on lib/widgets/alarms_widget.dart
> +        margin: const EdgeInsets.all(20),
I'll request changes now for this, sorry, but it's fast enough and it will be easier to do now rather than later. 

_Also, it's not like this will be merged into main before the meeting,,,_

2024-05-11 08:59 UTC, LeanderCretegny commented on lib/views/alarm_wizard.dart
> +    assetAudio = "assets/audio/boom.mp3";
I think this is out of the scope of this PR, but is not a bad idea. I would suggest to talk about it with everyone, and in case it is validated open a new PR.

2024-05-11 09:06 UTC, LeanderCretegny commented on lib/views/alarm_wizard.dart
> +      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
Yes no problem, but please next time try to do these comment sooner as I did asked several time for feedback on the telegram group, but had no answer :'(.

2024-05-11 09:13 UTC, LeanderCretegny commented on lib/widgets/alarms_widget.dart
> +        margin: const EdgeInsets.all(20),
Yes sorry, this code is in fact a refactor of a widget made by someone else for the alarm settings, and I admit that I did not really take a look at the details, I will do the requested changes asap

2024-05-11 15:48 UTC, pmdlt commented on lib/views/alarm_wizard.dart
> +    assetAudio = "assets/audio/boom.mp3";
Maybe the user doesn't want to bother with it in unboarding, but it definitely needs to be included in the settings.

2024-05-13 18:29 UTC, quartztz submitted a review, later dismissed

2024-05-15 14:59 UTC, Pacsort17 commented on lib/widgets/alarms_widget.dart
> +          microsecond: 0,
Why 0 seconds / milliseconds / microseconds ?

2024-05-15 15:13 UTC, Pacsort17 requested changes
During the onboarding, the navigation loops infinitely (when pressing next) over the "Choose your interests" and "Choose your provider" views

2024-05-15 18:21 UTC, Thechi2000 reviewed
Awesome job, thank you so much ! The code is really clean (just a few nit pick as usual), and the UI is good. Tested on Android.

I just have one issue with the UI: the "Alarm is set for tomorrow" and "Alarm not set" seems to be randomly updated when using the different controls, which is really not UX friendly. I'm also not sure about the point of it, since it will be set when tapping on "Done", right ?

2024-05-15 18:21 UTC, Thechi2000 commented on lib/views/news_alert_setup_view.dart
> +                          key: const Key("Switch-on-off"),
Until now, we've used "kebab-case" for keys, it would be good practice to continue with the same.

2024-05-15 18:21 UTC, Thechi2000 commented on lib/views/news_alert_setup_view.dart
> +                      key: const Key("Switch-loop"),
Same as above: Until now, we've used "kebab-case" for keys, it would be good practice to continue with the same.

2024-05-15 18:21 UTC, Thechi2000 commented on lib/views/news_alert_setup_view.dart
> +                      key: const Key("Switch-vibrate"),
Same as above: Until now, we've used "kebab-case" for keys, it would be good practice to continue with the same.

2024-05-15 18:21 UTC, Thechi2000 commented on lib/views/providers_wizard_view.dart
Thanks for the refactor and fixes !

2024-05-15 18:21 UTC, Thechi2000 commented on lib/widgets/alarms_widget.dart
> +      fillColor: THEME_BUTTON, //Colors.grey[200],
```suggestion
      fillColor: THEME_BUTTON,
```

Not sure about the comment here, it can be misleading especially if we change the value of the constant later on.

2024-05-15 18:21 UTC, Thechi2000 commented on lib/widgets/alarms_widget.dart
> +import 'dart:ffi';
```suggestion
```

This import is unused.

2024-05-15 18:21 UTC, Thechi2000 commented on lib/main.dart
> +import 'package:actualia/views/alarm_wizard.dart';
```suggestion
```

The import is unused.

2024-05-15 18:21 UTC, Thechi2000 commented on test/widgets/profile_view.dart
> +    await tester.tap(find.byKey(const Key("Switch-vibrate")));
Same as above: Until now, we've used "kebab-case" for keys, it would be good practice to continue with the same.

2024-05-15 18:58 UTC, LeanderCretegny commented
> I just have one issue with the UI: the "Alarm is set for tomorrow" and "Alarm not set" seems to be randomly updated when using the different controls, which is really not UX friendly. I'm also not sure about the point of it, since it will be set when tapping on "Done", right ?

This is indeed an issue, but that has nothing to do with this PR. This PR is only about the onboarding, not the settings.

2024-05-15 19:13 UTC, Thechi2000 approved these changes
Nice, let's merge that :)

2024-05-15 19:38 UTC, Pacsort17 approved these changes
Tested on Android, the alarm can be setup during the onboarding (and it rings), thanks for the job !

2024-05-15 19:56 UTC, merged