fix: fix body sent for generate-transcript
ActualIA/app pull request #156
Opened 2024-05-14 21:36 UTC by Thechi2000

Fixes the call to `generate-transcript`, since it requires a JSON body.

2024-05-14 22:26 UTC, pmdlt submitted a review, later dismissed

2024-05-15 08:38 UTC, quartztz requested changes
Incredible PR ! However, not above style guides. Please revise quickly! It's blocking for many other PRs.

2024-05-15 08:38 UTC, quartztz commented on lib/viewmodels/news.dart
> +    print("suzdgfshidufh");
incredible work on the PR, but You Are Not Above Stylistic Guidelines. 

please remove stray prints. 

or else.

2024-05-15 08:38 UTC, quartztz commented on test/integration/sources.dart
> +            "date": DateTime.now().toIso8601String(),
Can't believe this was the source of the bug...

Oh well ! Glad it's fixed now :D

2024-05-15 08:41 UTC, Thechi2000 commented on lib/viewmodels/news.dart
> +    print("suzdgfshidufh");
oopsie, thanks

2024-05-15 08:43 UTC, quartztz approved these changes

2024-05-15 08:59 UTC, pmdlt approved these changes

2024-05-15 08:59 UTC, merged