155 feat discover rss providers from url
ActualIA/app pull request #158
Opened 2024-05-15 20:03 UTC by Thechi2000

Add RSS feed discovery on client side by two methods:
1. Appending predefined pathes to the URL provided by the user.
2. Scraping the HTML of the document at the URL, looking for any URL containing "rss" or "feed", then checking if they are actual feeds.

Closes #155

2024-05-15 21:05 UTC, ClementJosso submitted a review, later dismissed
As always very clean code. I have tried theses new settings both with a valid news site (i.e. that has an RSS feed), in which case I got a correct scraping and interesting news, and when I entered an invalid URL I got the error message in red. Great work!

2024-05-16 08:01 UTC, pmdlt requested changes
Some minor questions/changes suggested !
Thanks for the job :)

2024-05-16 08:01 UTC, pmdlt commented on lib/models/providers.dart
> +        return const Right(["Unable to find related rss feed"]);
```suggestion
        return const Right(["Unable to find related RSS feed. Please provide the complete URL instead."]);
```

2024-05-16 08:02 UTC, pmdlt commented on lib/models/providers.dart
> +  static const paths = [
But I don't know if it's worth adding to the loop, it affects performance already.

2024-05-17 10:03 UTC, Thechi2000 commented on lib/models/providers.dart
> +      return document.findAllElements("rss").isNotEmpty;
Great idea ! I just added it.

2024-05-17 10:04 UTC, Thechi2000 commented on lib/models/providers.dart
> +  static const paths = [
The requests are done in parallel, so it won't affect much.

2024-05-17 10:24 UTC, ClementJosso approved these changes
I see you did dependency injection, great test practice

2024-05-17 10:44 UTC, pmdlt approved these changes
Thanks for the changes and the answers to my questions :)
Looks good to proceed!

2024-05-17 10:44 UTC, merged