160 Implement raw RSS view
ActualIA/app pull request #164
Opened 2024-05-17 07:44 UTC by quartztz

According to our new user story, we want to be able to inspect every news fed to the LLM, as if it were an RSS feed. This view implements just that ! 

For now, lacks a ViewModel to plug into the backend. Coming today !

2024-05-29 08:17 UTC, LeanderCretegny requested changes
Overall pretty great, a lot of small refactor that are much appreciated, my only concerns are about some view that imo could be stateless widget instead of statefull ones.

2024-05-29 08:17 UTC, LeanderCretegny commented on lib/viewmodels/rss_feed.dart
> +  geRawNewsList() async {
This looks like a small typo

2024-05-29 08:17 UTC, LeanderCretegny commented on lib/views/rss_feed_view.dart
> +  State<FeedView> createState() => _FeedViewState();
small nitpick, until now and as far as I know, the naming conventions we followed did not bother adding the extra State at the end of the class name, _FeedView is enough.

2024-05-29 08:17 UTC, LeanderCretegny commented on lib/views/rss_feed_view.dart
I think this view could be Stateless, it does not seem to hold any state.

2024-05-29 08:17 UTC, LeanderCretegny commented on lib/views/source_view.dart
> +  const SourceView({this.article = const Article(), super.key});
Wouldn't it make more sense to set the article parameter as required instead of providing a default one?

2024-05-29 08:17 UTC, LeanderCretegny commented on lib/views/source_view.dart
I don't think it is in the scope of this PR but it is worth mentioning, it seems to me that the SourceView could also be a stateless widget

2024-06-02 08:49 UTC, LeanderCretegny requested changes
Overall good code with much appreciated refactor, except in the ArticleWidget widget for which I am asking some changes about the unnecessary use of ListView instead of Column.

2024-06-02 08:49 UTC, LeanderCretegny commented on lib/views/rss_feed_view.dart
> +        const LoadingView(text: "Please wait while we fetch the news for you.");
Shouldn't it be localized?

2024-06-02 08:49 UTC, LeanderCretegny commented on lib/widgets/sources_view_widgets.dart
> +      super.key});
Wouldn't it be better to use the Article class and have only one attribute instead of 5?

2024-06-02 08:49 UTC, LeanderCretegny commented on lib/widgets/sources_view_widgets.dart
> +      physics: const NeverScrollableScrollPhysics(),
Please use ListView only when you need a scrollable list, consider using Column when it is not the case.

2024-06-02 08:49 UTC, LeanderCretegny commented on lib/widgets/sources_view_widgets.dart
> +            physics: const NeverScrollableScrollPhysics(),
Same comment as above

2024-06-02 08:49 UTC, LeanderCretegny commented on lib/widgets/sources_view_widgets.dart
Upon testing on the emulator I found one weird thing. The widget `ScrollableText` does not seem to be scrollable, I think this is due to the text being to short to be scrolled, but then why bother with creating this widget, maybe it is plan in the future to have bigger text?

2024-06-02 09:10 UTC, quartztz commented on lib/main.dart
> +          home = const LoadingView(text: 'Fetching your settings...');
Whoops ! not sure how that happened, i never had it on my machine. At any rate, that can be changed quickly !

2024-06-02 09:11 UTC, quartztz commented on lib/views/rss_feed_view.dart
> +        const LoadingView(text: "Please wait while we fetch the news for you.");
Right ! Missed that one.

2024-06-02 15:44 UTC, LeanderCretegny approved these changes

2024-06-02 15:45 UTC, LaClimSx requested changes

2024-06-02 15:45 UTC, LaClimSx commented on lib/widgets/sources_view_widgets.dart
> +      children: <Widget>[
I think this should have NeverScrollable physics, since this listView will be nested in another one

2024-06-02 16:37 UTC, quartztz commented
Thanks for handling it Clément !

2024-06-02 16:43 UTC, LaClimSx approved these changes
The scroll works now, and apart from that, the RSS view is fully functional, thanks for that!

2024-06-02 16:50 UTC, LeanderCretegny approved these changes

2024-06-02 16:52 UTC, merged