175 feat sharing fine tuning
ActualIA/app pull request #182
Opened 2024-05-24 18:24 UTC by pmdlt

2024-05-27 19:13 UTC, LaClimSx commented on lib/l10n/app_en.arb
> +  "newsShareText": "This personalized news has been generated by ActualIA, your daily companion for updates that matters to you.",
I think you mean "matter to you" if you're talking about the updates

2024-05-27 19:45 UTC, LaClimSx reviewed
I got this error when sharing the link to my transcript and opening it on my browser : 
![image](https://github.com/ActualIA/app/assets/93340253/c4cb23f8-0d76-47cd-ab82-0349e15034b0)

2024-05-28 11:20 UTC, Thechi2000 requested changes
Nice trick to get a minimal website ! Although, how have you set up the redirect on `actualia.pages.dev` ? I see that it actually returns the `supabase/website/index.html` file, but it would be great for it to be at least documented.

2024-05-28 11:20 UTC, Thechi2000 commented on supabase/functions/return-share-page/index.ts
> +});
I think it would be interesting to pass the sliced transcript, to have paragraphs and links for each sections.

2024-05-28 11:20 UTC, Thechi2000 commented on supabase/functions/return-share-page/index.ts
> +        <div class="input">${title}</div>
I don't like having the `input` class. This adds a search bar icon left to the title, which is very confusing since it is not usable. The title could also be a bit bigger, right now it has the same size as the text.

2024-05-28 11:20 UTC, Thechi2000 commented on .github/workflows/supabase.yml
> +      - run: supabase functions deploy --project-ref $PROJECT_ID generate-raw-feed
Are those linked to this PR ?

2024-05-28 11:20 UTC, Thechi2000 commented on supabase/functions/return-share-page/index.ts
> +      { status: 200, headers: { "Content-Type": "html" } },
It could have a more meaningful error code (404).

2024-05-28 11:20 UTC, Thechi2000 commented on supabase/functions/return-share-page/index.ts
> +      { status: 200, headers: { "Content-Type": "html" } },
It could have a more meaningful error code (403).

2024-05-28 11:20 UTC, Thechi2000 commented on supabase/functions/return-share-page/index.ts
> +    .single();
This query could be avoided if the `transcriptId` parameter was not given.

2024-05-28 17:11 UTC, pmdlt commented on lib/l10n/app_en.arb
> +  "newsShareText": "This personalized news has been generated by ActualIA, your daily companion for updates that matters to you.",
Yes sure, modified

2024-05-28 17:26 UTC, pmdlt commented on supabase/functions/return-share-page/index.ts
> +});
I'm not so sure about that, I'd rather show that we have a text transcript that's a little different from what the app displays. And also, people will wonder why this format is so intriguing, so it's good marketing.

2024-05-28 17:28 UTC, pmdlt commented on supabase/functions/return-share-page/index.ts
> +        <div class="input">${title}</div>
I've really used [this mockup](https://daisyui.com/components/mockup-browser/), and I don't intend to modify the rendering of the web page, it's really secondary to me. If you're motivated, don't hesitate to commit to this PR directly.
The idea is to make a PoC, not a polished thing.

2024-05-28 17:29 UTC, pmdlt commented on .github/workflows/supabase.yml
> +      - run: supabase functions deploy --project-ref $PROJECT_ID generate-raw-feed
No, it was just a deployment oversight in the others. I forgot to put a note to clarify, done now!

2024-05-28 17:31 UTC, pmdlt commented on supabase/functions/return-share-page/index.ts
> +      { status: 200, headers: { "Content-Type": "html" } },
I agree. Done!

2024-05-28 17:31 UTC, pmdlt commented on supabase/functions/return-share-page/index.ts
> +      { status: 200, headers: { "Content-Type": "html" } },
I agree. Done!

2024-05-28 17:32 UTC, pmdlt commented on supabase/functions/return-share-page/index.ts
> +    .single();
I agree. Done!

2024-05-28 17:43 UTC, pmdlt commented
> I got this error when sharing the link to my transcript and opening it on my browser

Yes, I forgot to add the querie that makes the news public. I've done it now! Note that the user can't make the news private after having made it public, this maybe needs to be implemented in the future.

2024-05-28 17:47 UTC, pmdlt commented
> Nice trick to get a minimal website ! Although, how have you set up the redirect on `actualia.pages.dev` ? I see that it actually returns the `supabase/website/index.html` file, but it would be great for it to be at least documented.

The site is deployed on Cloudflare by hand, the only file is the one added to the repo. I've put it in the supabase folder, as it acts a bit like a backend.

2024-05-28 18:37 UTC, Thechi2000 commented on supabase/functions/return-share-page/index.ts
> +});
Then, I think it would be great to at least provide the list of sources under the transcript, but this may be delayed to a later refactor since it is only a PoC.

2024-05-28 18:43 UTC, Thechi2000 reviewed
Thanks for the changes, all good now ! 

Good point that this is only a PoC, we should not bother about style. A later PR may improve the following points (I'm leaving it there for future reference):
- Improve CSS for better render
- Display sources

> The site is deployed on Cloudflare by hand, the only file is the one added to the repo. I've put it in the supabase folder, as it acts a bit like a backend.

Thanks for the info ! Could you add it to the README in the supabase folder ? I think it would be great for documentation.

2024-05-28 18:52 UTC, LaClimSx submitted a review, later dismissed
Thanks for the changes, the web app works now!

2024-05-28 18:56 UTC, pmdlt commented
> Thanks for the changes, all good now !
> 
> Good point that this is only a PoC, we should not bother about style. A later PR may improve the following points (I'm leaving it there for future reference):
> 
> * Improve CSS for better render
> * Display sources
> 
> > The site is deployed on Cloudflare by hand, the only file is the one added to the repo. I've put it in the supabase folder, as it acts a bit like a backend.
> 
> Thanks for the info ! Could you add it to the README in the supabase folder ? I think it would be great for documentation.

Done! https://github.com/ActualIA/app/commit/ef0d597f7b4df521d05801b584d59f7f04015725

2024-05-28 18:56 UTC, LaClimSx approved these changes

2024-05-28 19:33 UTC, merged