refactor: refactor wizard bottom bar
ActualIA/app pull request #184
Opened 2024-05-25 18:00 UTC by LeanderCretegny

Handle the refactor of the bottom bar in the wizard. The bottom bar is now handle in a scaffold as it should be.

To test: run the ci locally and run the code on a android phone, and either go through the onboarding or go in the settings to see the changes made.

This PR closes #176

2024-05-25 19:16 UTC, quartztz requested changes
Thank you for the much needed rework ! I left a few comments but they're all pretty benign and fast to fix. Let me know if you have any questions !

2024-05-25 19:34 UTC, LeanderCretegny commented on lib/views/interests_wizard_view.dart
> +  void setListState<T>(T item, List<T> list) {
You are right, but I feel like the name should reflect the use of set state in priority. I would suggest renaming it to `updateListStateOnSelection`.

2024-05-25 19:45 UTC, LeanderCretegny commented on lib/widgets/wizard_widgets.dart
> +            child: FadingEdgeScrollView.fromSingleChildScrollView(
For the fading on the top I'm not sure if this package allow it. I will look a bit more into it but can't guarantee that I'll find something.

2024-05-26 11:32 UTC, Thechi2000 reviewed
I like the new UI, thanks ! Just a few comments about localization, now that it has been merged.

Also, what do you think about adding a `Back` button to go to the previous selector (e.g. from interests to cities) ? Could that be implemented easily ? Don't bother if it is too complex, it's just a suggestion since you are working on refactoring this.

2024-05-26 11:32 UTC, Thechi2000 commented on lib/views/alarm_wizard.dart
> +      cancelText: "Skip",
This needs to be localized (as per #174).

2024-05-26 11:32 UTC, Thechi2000 commented on lib/views/interests_wizard_view.dart
> +        rText: "Next",
This needs to be localized (as per #174).

2024-05-26 11:32 UTC, Thechi2000 commented on lib/views/interests_wizard_view.dart
> +        rText: auth.isOnboardingRequired ? "Next" : "Finish",
This needs to be localized (as per #174).

2024-05-26 11:32 UTC, Thechi2000 commented on lib/views/providers_wizard_view.dart
> +      rText: auth.isOnboardingRequired ? "Next" : "Done",
This needs to be localized (as per #174).

2024-05-26 11:32 UTC, Thechi2000 commented on lib/views/alarm_wizard.dart
> +      rText: "Validate",
This needs to be localized (as per #174).

2024-05-26 11:32 UTC, Thechi2000 commented on lib/views/interests_wizard_view.dart
> +        rText: "Next",
This needs to be localized (as per #174).

2024-05-26 17:14 UTC, LeanderCretegny commented
Regarding the back button, it is present (but I am removing it in the #188). User can still go back by swiping to the left, but I don't think it is a behavior that should be encouraged.

2024-05-29 00:28 UTC, Thechi2000 approved these changes
LGTM !

2024-05-29 13:41 UTC, quartztz approved these changes
All good to me as well ! can be merged

2024-05-29 14:10 UTC, merged