185 refactor onboarding remove user button
ActualIA/app pull request #188
Opened 2024-05-26 15:40 UTC by LeanderCretegny

This PR removes user button in onboarding, as well as redundant back button, and fix some tests to fit the UI changes.

Testing: go through the onboarding and/or the settings to check that the views are not displaying the user button and back button anymore.

2024-05-26 15:43 UTC, Thechi2000 requested changes
Small and efficient, thanks ! Although it is missing the internationalization.

2024-05-26 15:43 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +      this.body = const Text("unimplemented"),
Should use the localized version (as per #174)

2024-05-26 15:43 UTC, Thechi2000 commented on test/integration/onboarding.dart
> +    await tester.tap(find.text("Skip"));
Should use the localized version (as per https://github.com/ActualIA/app/pull/174)

2024-05-26 15:46 UTC, LeanderCretegny commented on lib/widgets/wizard_widgets.dart
> +      this.body = const Text("unimplemented"),
I don't see why, there is no displayed text here (the text saying "unimplemented" is for dev only, as it is a placeholder)

2024-05-26 15:47 UTC, LeanderCretegny commented on test/integration/onboarding.dart
> +    await tester.tap(find.text("Skip"));
Is it really necessary inside a test?

2024-05-26 15:49 UTC, Thechi2000 commented on test/integration/onboarding.dart
> +    await tester.tap(find.text("Skip"));
Oh my bad, I didn't see it was in a test 😅

2024-05-26 15:49 UTC, Thechi2000 commented on lib/widgets/wizard_widgets.dart
> +      this.body = const Text("unimplemented"),
We did it until then, I think it would be good for consistency

2024-05-26 19:09 UTC, quartztz approved these changes
Much needed! Now it's consistent.

Thanks for localizing as well ! LGTM as is

2024-05-26 19:11 UTC, quartztz approved these changes
Much needed! Now it's consistent with expectations (and internationalized thanks to @Thechi2000's pedantry :) ). LGTM! Can be merged as is.

2024-05-26 19:11 UTC, quartztz submitted a review, later dismissed
Much needed! Now it's consistent with expectations (and internationalized thanks to @Thechi2000's pedantry :) ). LGTM! Can be merged as is.

2024-05-26 22:28 UTC, Thechi2000 requested changes
One last little thing, then it will be ready to merge imo

2024-05-26 22:28 UTC, Thechi2000 commented on lib/views/providers_wizard_view.dart
> +                Fluttertoast.showToast(msg: "Error while updating providers");
Nice catch for this nasty bug :)

However, you should not get rid of the localization of the message.

2024-05-29 11:57 UTC, Pacsort17 approved these changes
Small bug detected, but not related to this PR (I will open an issue)

Tested on Android, buttons are indeed removed.

2024-05-29 14:04 UTC, Thechi2000 approved these changes

2024-05-29 14:36 UTC, Pacsort17 approved these changes

2024-05-29 15:07 UTC, Thechi2000 approved these changes

2024-05-29 15:14 UTC, merged