feat: replace guest login with anonymous sign in option
ActualIA/app pull request #189
Opened 2024-05-26 15:43 UTC by quartztz

This pull request will modify the codebase's approach to anonymous/temporary users by using the existing [Anonymous Sign-In API](https://supabase.com/blog/anonymous-sign-ins) that's made available by Supabase Auth. This is a cleaner solution, as it allows users to use the app as intended without a Google Sign-In, with their own interests and so on, without impacting others in the same situation. 

Still in drafts !

A few things must be noted. 
> ℹ️  I had to modify the settings in the Supabase dashboard to explicitly allow Anonymous Sign-Ins. Be mindful of that !

> ⚠️ This inevitably opens us to security concerns that we didn't have earlier, such as potential botting practices or other exotic attacks through anonymous users. We might want to see how this interacts with our RLS, or if we want to add some sort of Captcha anti-bot behavior.

2024-05-29 05:55 UTC, Thechi2000 approved these changes
Awesome ! This will be useful both for showcasing, testing and production. Nothing to say about the code, it is clean and concise.

2024-05-29 13:07 UTC, pmdlt requested changes
Thanks for the work!

I think there are still 1-2 small things to do, including removing all traces of the old login form, and why not (I'll let you judge if it's relevant or not) indicate in the ui that the “sign in as a guest” is local, like : `Sign in as a guest (local account)` or something

2024-05-29 13:07 UTC, pmdlt commented on lib/models/auth_model.dart
>    Future<bool> signInWithFakeAccount() async {
```suggestion
  Future<bool> signInAnonymously() async {
```

2024-06-02 15:43 UTC, pmdlt commented on lib/models/auth_model.dart
>    Future<bool> signInWithFakeAccount() async {
Thanks for the changes!

2024-06-02 15:44 UTC, pmdlt approved these changes
Thanks for the changes!

2024-06-02 15:44 UTC, merged

2024-06-02 15:48 UTC, pmdlt reviewed
I merged too quickly, the requested changes were not made.