170 feat swipe up to regenerate news
ActualIA/app pull request #203
Opened 2024-05-31 18:41 UTC by LaClimSx

This PR introduces a new feature : We can now generate a new transcript by swiping down on the news view. This should display a small loading icon, and after some time show the new transcript at the top of the list. Also, when the user doesn't have any news, there isn't a button to generate news anymore, since the user can simply swipe to do it.

You can test this behavior by just launching the app and swiping down to see if it generates a news transcript.

2024-06-01 06:16 UTC, Thechi2000 requested changes

2024-06-01 06:16 UTC, Thechi2000 commented on lib/models/offline_recorder.dart
You seems to have added carriage returns to the file (because you are using Windows). Please remove them for consistency. You can also change your git settings to automatically correct it to avoid any issue (see [here](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace)).

2024-06-01 06:16 UTC, Thechi2000 commented on lib/l10n/app_en.arb
> +  "newsEmptyDescription": "The first one will be generated the first time the alarm goes off. You can also generate a transcript by swiping down.",
I feel like "refreshing the page" would be more intuitive than "swiping down", but I'm not sure about it. What do you think ?

2024-06-01 06:16 UTC, Thechi2000 commented on lib/l10n/app_fr.arb
> +    "newsEmptyDescription": "La première sera générée lorsque votre alarme s'activera. Vous pouvez également en générer manuellement en défilant vers le bas.",
Same as above

2024-06-01 20:31 UTC, Thechi2000 approved these changes
LGTM !

2024-06-01 21:50 UTC, loggerz commented on lib/l10n/app_en.arb
> +  "newsEmptyDescription": "The first one will be generated the first time the alarm goes off. You can also generate a transcript by swiping down.",
What I like about the "swiping down" is that it's expressive : you know what to do to refresh. I suggest we keep it that way

2024-06-02 09:05 UTC, Thechi2000 submitted a review, later dismissed

2024-06-02 09:08 UTC, quartztz submitted a review, later dismissed
Looks good to me ! Can be merged, nice UX feature

2024-06-02 11:56 UTC, quartztz approved these changes
Dismissed because of a merge, but the point still stands ! good feature

2024-06-02 12:14 UTC, Pacsort17 approved these changes
I don't know why but my previous review isn't shown in the history, so I'll right it down here.

This is a nice feature ! Tested on Android, it works well and it is userfriendly.
As I told before, a test could have been added for checking that previous news from the same day are still displayed (which is the case currently).

It is also a little bit slow, but it is bottleneck by the LLM so there is not much we can do about it.

2024-06-02 12:14 UTC, merged