76 feat add audio generation
ActualIA/app pull request #77
Opened 2024-04-16 20:33 UTC by pmdlt

This PR introduces functionality to generate audio files from transcripts stored in the database.

**Changes:**

Added a Deno server to handle HTTP requests.
Integrated Supabase for database operations.
Integrated the OpenAI API for text-to-speech functionality.
Implemented error handling for various scenarios.
Added support for specifying desired voice options.
Uploaded generated audio files to Supabase storage.
Updated database records with audio file paths.

**Purpose:**

The purpose of this PR is to automate the process of generating audio files from text transcripts.

2024-04-16 20:58 UTC, ClementJosso submitted a review, later dismissed
Great work!

2024-04-17 08:06 UTC, Thechi2000 requested changes
Works great, thanks !

I think we should have some tests, at least to cover errors for bad requests (missing parameters and so on). Since it is usable with the anon key, it is also possible to have tests for working case, but this may slow the CI (to discuss).

2024-04-18 14:57 UTC, Thechi2000 approved these changes

2024-04-18 17:00 UTC, ClementJosso approved these changes

2024-04-18 18:45 UTC, merged