85 update news view and viewmodel to display all the news of the user
ActualIA/app pull request #87
Opened 2024-04-18 20:57 UTC by ClementJosso

This PR changes the news in order to display all of the news (max 10)  a user has in the DB rather than just today's. It should look like this :
![image](https://github.com/ActualIA/app/assets/93340253/a826a7b9-2418-49e0-a689-0c701d81c529)
It would be nice if the reviewer could test it with both an account with multiple news on it, as well as an account which has no news for today, to see if it generates it correctly (these 2 types of account are not incompatible, one can satisfy both criteria).

2024-04-24 22:25 UTC, Thechi2000 requested changes
When running on Android, I get the following error with my personal account:
```
I/flutter ( 8533): Error fetching news list: type 'Null' is not a subtype of type 'String'
```

On the other hand, the guest account is stuck on the loading after sucessfully generating the transcript. I think this is due to a mistake in the `generateAndGetNews()` function, which only calls `fetchNews()` (see my comment).

2024-04-24 22:25 UTC, Thechi2000 commented on lib/viewmodels/news.dart
> +        generateAndGetNews();
```suggestion
        await generateAndGetNews();
```

2024-04-24 22:25 UTC, Thechi2000 commented on lib/viewmodels/news.dart
> +          generateAndGetNews();
```suggestion
          await generateAndGetNews();
```

2024-04-24 22:25 UTC, Thechi2000 commented on lib/viewmodels/news.dart
> +    await fetchNews(DateTime.now());
Shouldn't this be `fetchNewsList()`, since we are always dealing with multiple entries now ?

2024-04-25 10:32 UTC, ClementJosso commented on lib/viewmodels/news.dart
> +    await fetchNews(DateTime.now());
In my opinion not necessarily, we could use fetchNewsList(), but this function is actually only called when we need a single entry from the database, so fetchNews() works fine. Maybe in the future we can remove it if we decide to remove the single entry functions altogether, but at the moment I find it useful.

2024-04-25 10:36 UTC, ClementJosso commented on lib/viewmodels/news.dart
>    News? get news => _news;
Same here, the parameter news is actually still used because this is where the result of the single entry query is written. We could remove it and make it a return parameter of the query, but I'd rather wait for the offline part of the app to be implemented, because that will probably significantly impact the way this View Model interacts with the DB, so it's good to have everything at hand to know what to keep and what to remove once we have the offline storage.

2024-04-25 13:37 UTC, LeanderCretegny reviewed
I think that the code is good and work as intended, but I think that we should change the title for the news from previous days.

2024-04-25 13:47 UTC, LeanderCretegny approved these changes

2024-04-25 14:03 UTC, merged